# Generated by Django 3.1 on 2020-09-16 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200915_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers',
            new_name='follows',
        ),
    ]
